Fix secret parsing
Currently builds which use secrets will fail [1] with:
Error: GetSecret: pq: invalid input syntax for type uuid: "None"

That is caused by the uuid_or_string function never returning anything,
so the secrets array will simply consist of "None".

[1]: https://builds.sr.ht/~sircmpwn/job/947773